---
apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    fabric8.io/iconUrl: img/icons/spring-boot.svg
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=jboss-remote-query-quickstart&var-version=7.0.0.Final-redhat-1
    fabric8.io/scm-tag: HEAD
    fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/jboss-remote-query-quickstart
  labels:
    provider: fabric8
    project: jboss-remote-query-quickstart
    version: 7.0.0.Final-redhat-1
    group: org.jboss.quickstarts.jdg
  name: jboss-remote-query-quickstart
spec:
  replicas: 1
  selector:
    project: jboss-remote-query-quickstart
    provider: fabric8
    version: 7.0.0.Final-redhat-1
    group: org.jboss.quickstarts.jdg
  template:
    metadata:
      annotations:
        fabric8.io/iconUrl: img/icons/spring-boot.svg
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=jboss-remote-query-quickstart&var-version=7.0.0.Final-redhat-1
        fabric8.io/scm-tag: HEAD
        fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/jboss-remote-query-quickstart
      labels:
        provider: fabric8
        project: jboss-remote-query-quickstart
        version: 7.0.0.Final-redhat-1
        group: org.jboss.quickstarts.jdg
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JAVA_APP_DIR
          value: /deployments
        image: jboss-remote-query-quickstart:7.0.0.Final-redhat-1
        imagePullPolicy: IfNotPresent
        name: spring-boot
        ports:
        - containerPort: 8991
          name: https-wmap
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        securityContext:
          privileged: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - spring-boot
      from:
        kind: ImageStreamTag
        name: jboss-remote-query-quickstart:7.0.0.Final-redhat-1
    type: ImageChange
