---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: jboss-remote-query-quickstart
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: jboss-remote-query-quickstart@sha256:45dc352c46a3310d02c470b3e4297c8a83fb8df41c46677cde4c115777f7d156
        namespace: jboss-dg-poc
      name: 7.0.0.Final-redhat-1
